### ISSUE TITLE
v1.0.4 not working on Android

### ISSUE THREAD

**Issue by atulmy** [GetSimpl/react-native-simpl-zero-click-sdk#6]
"react-native-simpl-zero-click-sdk": "1.0.4",

react native android error: cannot find symbol simpl in `example/node_modules/react-native-simpl-zero-click-sdk/android/src/main/java/com/android/simplSdk/SimplSdkModule.java` on line https://github.com/GetSimpl/react-native-simpl-zero-click-sdk/pull/5/files#diff-c9a9d2a5f07c7483758a527dba65a666R70

**Comment by Kamalnrf** [comment]
my bad, I'll release a new version today to fix this.
